### ISSUE TITLE
seed-db.js no bueno

### ISSUE THREAD

**Issue by sbenthall** [yrevocnu/psychedelic-glass-bead-game#18]
`$ node bin/seed-db.js `

Error: https://gist.github.com/sbenthall/1c84e56dc8b66b3d114a670e0bef48d4

I'm trying to seed the DB. `MONGODB_URL` in `.env` is commented away.

No docs for how to use this script!

**Comment by sbenthall** [comment]
Oh, I see. What I was supposed to do is run

`yarn seed:db`. This is documented.

However, I get the same error on this. Suggesting the docs are not up to date.

**Comment by benheller** [comment]
This has been resolved in 87bd9b9e8742455ab151fae27e9b43deb17cc150
