### ISSUE TITLE
!eval security audit

### ISSUE THREAD

**Issue by sbenthall** [yrevocnu/psychedelic-glass-bead-game#30]
There's reason to believe that the !eval discord bot endpoint introduces some security vulnerabilities.

These security vulnerabilities should be identified and patched.

**Comment by sbenthall** [comment]
@ben you mentioned some "potentially disastrous" uses of the endpoint in your review of PR #28 

I wonder if you had anything specific in mind.

**Comment by benheller** [comment]
@sbenthall see https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/eval#Never_use_eval!

However, now that we've talked, I understand the use case better. The safe way to do this is with https://nodejs.org/api/vm.html#vm_vm_runinthiscontext_code_options.

Example code:

```
const vm = require('vm');
let localVar = 'initial value';

const vmResult = vm.runInThisContext('localVar = "vm";');
console.log(`vmResult: '${vmResult}', localVar: '${localVar}'`);
// Prints: vmResult: 'vm', localVar: 'initial value'
```

At your convenience, please open a PR to address this.

**Comment by sbenthall** [comment]
This is quite interesting ... the VM library itself is largely about "context", specifically, the context in which code is executed, which in JavaScript can be specified from an object. (I.e., it's a scope).

Just as in functional programming, code is data, it's nice to remember that in JavaScript, objects are contexts.

This is quite promising as we have fun with hypercard rooms in the future. A card can be a picture. It can also be a scene in which other activities take place -- a context. And we can nest some contexts in others.

It looks like the VM mechanism will let us do this without giving away your credit card number to malicious actors.
